### ISSUE TITLE
Error compiling with VS2022 

### ISSUE THREAD

**Issue by leegramling** [PacktPublishing/The-Modern-Vulkan-Cookbook#11]
FAILED: source/chapter1/Chapter01_Triangle.exe 
  cmd.exe /C "cd . && "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_exe --intdir=source\chapter1\CMakeFiles\Chapter01_Triangle.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1437~1.328\bin\Hostx64\x64\link.exe /nologo source\chapter1\CMakeFiles\Chapter01_Triangle.dir\main.cpp.obj  /out:source\chapter1\Chapter01_Triangle.exe /implib:source\chapter1\Chapter01_Triangle.lib /pdb:source\chapter1\Chapter01_Triangle.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console -LIBPATH:C:\VulkanSDK\1.3.280.0\Include\..\lib   -LIBPATH:C:\Users\leegr\dev\The-Modern-Vulkan-Cookbook\out\build\x64-Debug\_deps\dlss-src\lib\Windows_x86_64\x86_64 source\vulkancore\VulkanCore.lib  out\build\x64-Debug\_deps\glfw-src\src\glfw3.lib  OSDependentd.lib  MachineIndependentd.lib  GenericCodeGend.lib  glslangd.lib  SPIRVd.lib  SPIRV-Toolsd.lib  SPIRV-Tools-optd.lib  glslang-default-resource-limitsd.lib  spirv-cross-cored.lib  spirv-cross-glsld.lib  spirv-cross-reflectd.lib  out\build\x64-Debug\_deps\spirvreflect-src\spirv-reflect-static.lib  _deps\tracy-build\TracyClient.lib  _deps\volk-build\volk.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
  LINK Pass 1: command "C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1437~1.328\bin\Hostx64\x64\link.exe /nologo source\chapter1\CMakeFiles\Chapter01_Triangle.dir\main.cpp.obj /out:source\chapter1\Chapter01_Triangle.exe /implib:source\chapter1\Chapter01_Triangle.lib /pdb:source\chapter1\Chapter01_Triangle.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console -LIBPATH:C:\VulkanSDK\1.3.280.0\Include\..\lib -LIBPATH:C:\Users\leegr\dev\The-Modern-Vulkan-Cookbook\out\build\x64-Debug\_deps\dlss-src\lib\Windows_x86_64\x86_64 source\vulkancore\VulkanCore.lib out\build\x64-Debug\_deps\glfw-src\src\glfw3.lib OSDependentd.lib MachineIndependentd.lib GenericCodeGend.lib glslangd.lib SPIRVd.lib SPIRV-Toolsd.lib SPIRV-Tools-optd.lib glslang-default-resource-limitsd.lib spirv-cross-cored.lib spirv-cross-glsld.lib spirv-cross-reflectd.lib out\build\x64-Debug\_deps\spirvreflect-src\spirv-reflect-static.lib _deps\tracy-build\TracyClient.lib _deps\volk-build\volk.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:source\chapter1\CMakeFiles\Chapter01_Triangle.dir/intermediate.manifest source\chapter1\CMakeFiles\Chapter01_Triangle.dir/manifest.res" failed (exit code 1104) with the following output:
C:\Users\leegr\dev\The-Modern-Vulkan-Cookbook\out\build\x64-Debug\LINK : fatal error LNK1104: cannot open file 'OSDependentd.lib'

the file exists here:
$ find . -name "OSDependentd.lib" -print
./out/build/x64-Debug/_deps/glslang-build/glslang/OSDependent/Windows/OSDependentd.lib

**Comment by askheaven101** [comment]
I have that problem, too.

**Comment by preetishkakkar** [comment]
You have to open root folder from VS, not the source folder, let me know if that helps.

**Comment by leegramling** [comment]
No that does not work:
leegr@devforge MINGW64 ~/dev
$ git clone https://github.com/PacktPublishing/The-Modern-Vulkan-Cookbook.git
Cloning into 'The-Modern-Vulkan-Cookbook'...
remote: Enumerating objects: 1604, done.
remote: Counting objects: 100% (99/99), done.
remote: Compressing objects: 100% (78/78), done.
remote: Total 1604 (delta 35), reused 53 (delta 15), pack-reused 1505
Receiving objects: 100% (1604/1604), 55.73 MiB | 3.86 MiB/s, done.
Resolving deltas: 100% (265/265), done.
Updating files: 100% (1290/1290), done.

leegr@devforge MINGW64 ~/dev
$ cd The-Modern-Vulkan-Cookbook
# I opened VS and did File->Open to ~/dev/The-Modern-Vulkan-Cookbook
# CMake  runs and when finished I did build and got the same error.

**Comment by preetishkakkar** [comment]
Are you using Visual studio 2022 or Visual studio code? We didn't use MINGW, so it mayn't work. You will have select below option from Visual studio 2022

![image](https://github.com/PacktPublishing/The-Modern-Vulkan-Cookbook/assets/18044006/82ca7541-9c58-4346-a0fb-d5259b8b5264)

**Comment by preetishkakkar** [comment]
Once open, you should see screen such as below, hope that helps

![image](https://github.com/PacktPublishing/The-Modern-Vulkan-Cookbook/assets/18044006/6923f6ab-1dbf-443c-b270-0a240c5009bc)

**Comment by leegramling** [comment]
Yes VS2022 version 4.8.09032,
Yes my solution folders look just like your picture.

**Comment by leegramling** [comment]
![Screenshot 2024-06-24 165404](https://github.com/PacktPublishing/The-Modern-Vulkan-Cookbook/assets/2179104/6b1b2a27-6b1f-4a57-b95d-85a00a206f5e)

**Comment by preetishkakkar** [comment]
Whats your VS version? Mine is 17.8.3, latest is 17.9.7, I am going to upgrade and try again.

**Comment by preetishkakkar** [comment]
The version you provided is for .NET

**Comment by preetishkakkar** [comment]
I tested with latest version and it works fine, can you provide which version of Vulkan SDK are you using? I am on 1.3.280.0

**Comment by leegramling** [comment]
17.7.5, I will upgrade to the latest also.
btw the MINGW64 was just my bash shell prompt.
I am wondering if you have your PATH set so that it finds the .lib file?
Also here is the compile line from the VS2022 output window:
>------ Build All started: Project: The-Modern-Vulkan-Cookbook, Configuration: x64-debug ------
  [0/2] Re-checking globbed directories...
  [1/32] cmd.exe /C "cd /D C:\Users\leegr\dev\The-Modern-Vulkan-Cookbook\out\build\x64-Debug\source\chapter2 && "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E copy_directory C:/Users/leegr/dev/The-Modern-Vulkan-Cookbook/source/chapter2/resources C:/Users/leegr/dev/The-Modern-Vulkan-Cookbook/out/build/x64-Debug/source/chapter2/resources"
  [2/32] Linking CXX executable source\chapter1\Chapter01_Triangle.exe
  FAILED: source/chapter1/Chapter01_Triangle.exe 
  cmd.exe /C "cd . && "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_exe --intdir=source\chapter1\CMakeFiles\Chapter01_Triangle.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1437~1.328\bin\Hostx64\x64\link.exe /nologo source\chapter1\CMakeFiles\Chapter01_Triangle.dir\main.cpp.obj  /out:source\chapter1\Chapter01_Triangle.exe /implib:source\chapter1\Chapter01_Triangle.lib /pdb:source\chapter1\Chapter01_Triangle.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console -LIBPATH:C:\VulkanSDK\1.3.280.0\Include\..\lib   -LIBPATH:C:\Users\leegr\dev\The-Modern-Vulkan-Cookbook\out\build\x64-Debug\_deps\dlss-src\lib\Windows_x86_64\x86_64 source\vulkancore\VulkanCore.lib  out\build\x64-Debug\_deps\glfw-src\src\glfw3.lib  OSDependentd.lib  MachineIndependentd.lib  GenericCodeGend.lib  glslangd.lib  SPIRVd.lib  SPIRV-Toolsd.lib  SPIRV-Tools-optd.lib  glslang-default-resource-limitsd.lib  spirv-cross-cored.lib  spirv-cross-glsld.lib  spirv-cross-reflectd.lib  out\build\x64-Debug\_deps\spirvreflect-src\spirv-reflect-static.lib  _deps\tracy-build\TracyClient.lib  _deps\volk-build\volk.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
  LINK Pass 1: command "C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1437~1.328\bin\Hostx64\x64\link.exe /nologo source\chapter1\CMakeFiles\Chapter01_Triangle.dir\main.cpp.obj /out:source\chapter1\Chapter01_Triangle.exe /implib:source\chapter1\Chapter01_Triangle.lib /pdb:source\chapter1\Chapter01_Triangle.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console -LIBPATH:C:\VulkanSDK\1.3.280.0\Include\..\lib -LIBPATH:C:\Users\leegr\dev\The-Modern-Vulkan-Cookbook\out\build\x64-Debug\_deps\dlss-src\lib\Windows_x86_64\x86_64 source\vulkancore\VulkanCore.lib out\build\x64-Debug\_deps\glfw-src\src\glfw3.lib OSDependentd.lib MachineIndependentd.lib GenericCodeGend.lib glslangd.lib SPIRVd.lib SPIRV-Toolsd.lib SPIRV-Tools-optd.lib glslang-default-resource-limitsd.lib spirv-cross-cored.lib spirv-cross-glsld.lib spirv-cross-reflectd.lib out\build\x64-Debug\_deps\spirvreflect-src\spirv-reflect-static.lib _deps\tracy-build\TracyClient.lib _deps\volk-build\volk.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:source\chapter1\CMakeFiles\Chapter01_Triangle.dir/intermediate.manifest source\chapter1\CMakeFiles\Chapter01_Triangle.dir/manifest.res" failed (exit code 1104) with the following output:
C:\Users\leegr\dev\The-Modern-Vulkan-Cookbook\out\build\x64-debug\LINK : fatal error LNK1104: cannot open file 'OSDependentd.lib'

**Comment by preetishkakkar** [comment]
No, that shouldn't be required, what is your Vulkan SDK version?

**Comment by leegramling** [comment]
C:\VulkanSDK\1.3.280.0

**Comment by leegramling** [comment]
Rebuilding with latest VS2022. 17.10.3
Microsoft Visual Studio Community 2022
Version 17.10.3
VisualStudio.17.Release/17.10.3+35013.160
Microsoft .NET Framework
Version 4.8.09032
Installed Version: Community
Visual C++ 2022   00482-90000-00000-AA266
Microsoft Visual C++ 2022

I do see a CMake warning about Vulkan:
1> [CMake] CMake Warning at C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.28/Modules/FindVulkan.cmake:526 (message):
1> [CMake]   Library SPIRV-Tools for Debug configuration is missing, imported target
1> [CMake]   Vulkan::SPIRV-Tools may not be able to link when targeting this build
1> [CMake]   configuration due to incompatible MSVC ABI.  Consider re-installing the
1> [CMake]   Vulkan SDK and request debug libraries to fix this warning.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.28/Modules/FindVulkan.cmake:548 (_Vulkan_set_library_component_found)
1> [CMake]   out/build/x64-Debug/_deps/volk-src/CMakeLists.txt:66 (find_package)
1> [CMake] 
1> [CMake] 
1> [CMake] volk: using Vulkan_INCLUDE_DIRS from FindVulkan module
1> [CMake] CMake Warning at C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.28/Modules/FindVulkan.cmake:526 (message):
1> [CMake]   Library SPIRV-Tools for Debug configuration is missing, imported target
1> [CMake]   Vulkan::SPIRV-Tools may not be able to link when targeting this build
1> [CMake]   configuration due to incompatible MSVC ABI.  Consider re-installing the
1> [CMake]   Vulkan SDK and request debug libraries to fix this warning.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.28/Modules/FindVulkan.cmake:548 (_Vulkan_set_library_component_found)
1> [CMake]   out/build/x64-Debug/_deps/vma-src/CMakeLists.txt:5 (find_package)

**Comment by preetishkakkar** [comment]
Probably delete your out folder and retry, also looks like some how Vulkan SDK path isn't set?

**Comment by leegramling** [comment]
![Screenshot 2024-06-24 180310](https://github.com/PacktPublishing/The-Modern-Vulkan-Cookbook/assets/2179104/9eaf3138-5476-4fce-8d37-d4d6596ec89c)

**Comment by leegramling** [comment]
I am re-installing vulkan to inclue the debug shader toolchain

**Comment by leegramling** [comment]
It now builds, Iuninstalled and reinstalled Vulkan with all debug options as pictured above.
Closed VS2022, and deleted my out directory.
Reopened vs2022 and let CMake generate files.
Built All, and it all built :)
Thanks for your help, I hope this helps others.

**Comment by leegramling** [comment]
![Screenshot 2024-06-24 181647](https://github.com/PacktPublishing/The-Modern-Vulkan-Cookbook/assets/2179104/85cf8ea6-ae32-43d6-bf37-767848590d0f)

**Comment by preetishkakkar** [comment]
Great! Glad to see its working! Closing the issue now.

**Comment by AmilaCG** [comment]
I also ran into the same issue. Instead of reinstalling the Vulkan SDK, I selected Modify and only added the required components.

![image](https://github.com/user-attachments/assets/6235db48-3bf2-49a3-bd0b-81aa674a974f)

**Comment by JTLee98** [comment]
was dealing with this myself just now, like @AmilaCG noticed it seems like an issue with how the vulkan SDK is installed on windows:

```cmake
    # For Windows Vulkan SDK, third party tools binaries are provided with different MSVC ABI:
    #   - Release binaries uses a runtime library
    #   - Debug binaries uses a debug runtime library
    # This lead to incompatibilities in linking for some configuration types due to CMake-default or project-configured selected MSVC ABI.
    if(WIN32 AND NOT _ARG_NO_WARNING)
      if(NOT Vulkan_${component}_LIBRARY)
        message(WARNING
"Library ${component} for Release configuration is missing, imported target Vulkan::${component} may not be able to link when targeting this build configuration due to incompatible MSVC ABI.")
      endif()
      if(NOT Vulkan_${component}_DEBUG_LIBRARY)
        message(WARNING
"Library ${component} for Debug configuration is missing, imported target Vulkan::${component} may not be able to link when targeting this build configuration due to incompatible MSVC ABI. Consider re-installing the Vulkan SDK and request debug libraries to fix this warning.")

``` 
(from https://github.com/Kitware/CMake/blob/d769493bf2b2c892faf2e8f35638ef46ea3dc4c9/Modules/FindVulkan.cmake#L516)

so yes, it can be fixed by running the vulkan sdk maintenance tool and additionally installing the required debug or release libraries. I think it would be good to mention this in the readme for this repo.
