### ISSUE TITLE
Unable to Access Bistro.glb - Data Quota Reached

### ISSUE THREAD

**Issue by ryco117** [PacktPublishing/The-Modern-Vulkan-Cookbook#13]
Hello, I am trying to access the `Bistro.glb` to test my ray tracing implementation. However, I am seeing the following error.
```
$ git lfs fetch
fetch: Fetching reference refs/heads/main
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/PacktPublishing/The-Modern-Vulkan-Cookbook.git/info/lfs'
```

I'd appreciate very much if the model can be shared on LFS or hosted elsewhere for users to access.
Thanks

**Comment by preetishkakkar** [comment]
The readme file on the front page of repo already talks about it. Here are steps, let me know if there is better place to put this.

If you encounter an error related to the LFS (Large File Storage) file Bistro.glb while cloning the repository, the error might look like this: Error downloading object: source/common/resources/assets/Bistro.glb: Smudge error

1.) set GIT_LFS_SKIP_SMUDGE=1 on terminal
2.) git clone https://github.com/PacktPublishing/The-Modern-Vulkan-Cookbook.git
3.) Download Bistro.glb from https://1drv.ms/u/s!AsOHFR8SHZcxhONARRHaUFqKd8BXOA?e=KsdErS and copy it in source/common/resources/assets, replace existing Bistro.glb with the new one you downloaded.
By following these steps, you should be able to clone the repository and resolve any LFS-related errors with the Bistro.glb file.

**Comment by ryco117** [comment]
My bad, you are correct.
