### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by wqycg** [PacktPublishing/The-Modern-Vulkan-Cookbook#9]
Open folder in vs2022, wait cmake configuration, then select `Chapter01_Triangle.exe` to execute.
<img width="276" alt="image" src="https://github.com/PacktPublishing/The-Modern-Vulkan-Cookbook/assets/25783139/432c2075-f8ef-438c-9810-5224769e8711">

**Comment by AmilaCG** [comment]
I'm also having the same issue. Did you find a solution for this?

**Comment by preetishkakkar** [comment]
@AmilaCG - See if this helps -> https://github.com/PacktPublishing/The-Modern-Vulkan-Cookbook/issues/11, otherwise we are connected on LinkedIn, feel free to message me there
